const http=require('http');const fs=require('fs');const path=require('path');const crypto=require('crypto');const {URL}=require('url');
const ROOT=__dirname, DATA=path.join(ROOT,'data','db.json'), PUBLIC=path.join(ROOT,'public');
const PORT=process.env.PORT||3000;
const ROLES=['Admin','Manager','SalesExecutive'];
const dbDefault={users:[],customers:[],leads:[],opportunities:[],followups:[],activities:[],audit:[],sessions:{}};
function load(){try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch(e){fs.mkdirSync(path.dirname(DATA),{recursive:true});fs.writeFileSync(DATA,JSON.stringify(dbDefault,null,2));return structuredClone(dbDefault)}}
let db=load();function save(){fs.writeFileSync(DATA,JSON.stringify(db,null,2))}
function id(prefix){return prefix+'_'+crypto.randomBytes(5).toString('hex')}
function now(){return new Date().toISOString()}
function hashPassword(p,salt){return crypto.scryptSync(p,salt,64).toString('hex')}
function makePassword(p){const salt=crypto.randomBytes(16).toString('hex');return salt+':'+hashPassword(p,salt)}
function checkPassword(p,stored){try{const [salt,h]=stored.split(':');return crypto.timingSafeEqual(Buffer.from(hashPassword(p,salt),'hex'),Buffer.from(h,'hex'))}catch{return false}}
function seed(){if(db.users.length)return;db.users=[
 {id:'u_admin',name:'System Admin',email:'admin@acxiomcrm.local',passwordHash:makePassword('Admin@123'),role:'Admin',active:true,failed:0,lockoutEnd:null,createdAt:now()},
 {id:'u_manager',name:'Sales Manager',email:'manager@acxiomcrm.local',passwordHash:makePassword('Manager@123'),role:'Manager',active:true,failed:0,lockoutEnd:null,createdAt:now()},
 {id:'u_sales',name:'Sales Executive',email:'sales@acxiomcrm.local',passwordHash:makePassword('Sales@123'),role:'SalesExecutive',active:true,failed:0,lockoutEnd:null,createdAt:now()}
 ];save()}seed();
const sessions=db.sessions;
function send(res,status,obj,headers={}){res.writeHead(status,{'Content-Type':'application/json',...headers});res.end(JSON.stringify(obj))}
function html(res,file){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(fs.readFileSync(path.join(PUBLIC,file)))}
function parseCookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{const i=x.indexOf('=');return [x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
function body(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e6)req.destroy()});req.on('end',()=>{try{resolve(s?JSON.parse(s):{})}catch(e){resolve({})}});req.on('error',reject)})}
function user(req){const sid=parseCookies(req).sid;const s=sid&&sessions[sid];if(!s)return null;if(s.expires<Date.now()){delete sessions[sid];save();return null}return db.users.find(u=>u.id===s.userId)||null}
function audit(u,action,entity,recordId,result='Success',details=''){db.audit.unshift({id:id('audit'),userId:u?.id||null,action,entityName:entity,recordId:recordId||null,oldValue:null,newValue:null,createdDate:now(),ipAddress:'local',result,details});db.audit=db.audit.slice(0,1000);save()}
function requireAuth(req,res){const u=user(req);if(!u)return send(res,401,{error:'Authentication required'});if(!u.active)return send(res,403,{error:'Account inactive'});return u}
function requireRole(req,res,roles){const u=requireAuth(req,res);if(!u||res.writableEnded)return null;if(!roles.includes(u.role))return send(res,403,{error:'Forbidden'}),null;return u}
function visible(u,item){return u.role!=='SalesExecutive'||item.assignedTo===u.id||item.ownerId===u.id||item.createdBy===u.id}
function validateEmail(x){return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(x||'')}
function validatePhone(x){return /^[6-9]\d{9}$/.test(x||'')}
function validateBase(d){if(!d.name||d.name.trim().length<2)return 'Name is required.';if(d.email&&!validateEmail(d.email))return 'Enter a valid email address.';if(d.phone&&!validatePhone(d.phone))return 'Enter a valid phone number.';return null}
function listBy(req,res,key){const u=requireAuth(req,res);if(!u||res.writableEnded)return;let arr=db[key].filter(x=>visible(u,x));const q=new URL(req.url,'http://x').searchParams.get('q');if(q){const z=q.toLowerCase();arr=arr.filter(x=>JSON.stringify(x).toLowerCase().includes(z))}send(res,200,arr)}
async function api(req,res){const url=new URL(req.url,'http://localhost');const p=url.pathname;const method=req.method;const b=await body(req);
 if(p==='/api/auth/login'&&method==='POST'){const email=(b.email||'').toLowerCase().trim();const u=db.users.find(x=>x.email.toLowerCase()===email);if(!u){audit(null,'Failed Login','User',null,'Failed','Unknown user');return send(res,401,{error:'Invalid credentials'})}if(u.lockoutEnd&&new Date(u.lockoutEnd)>new Date())return send(res,423,{error:'Account temporarily locked'});if(!u.active)return send(res,403,{error:'Account inactive'});if(!checkPassword(b.password||'',u.passwordHash)){u.failed=(u.failed||0)+1;if(u.failed>=5){u.lockoutEnd=new Date(Date.now()+15*60000).toISOString();audit(u,'Lockout','User',u.id,'Success','5 failed login attempts');}else audit(u,'Failed Login','User',u.id,'Failed','Invalid password');save();return send(res,401,{error:'Invalid credentials'})}u.failed=0;u.lockoutEnd=null;const sid=crypto.randomBytes(32).toString('hex');sessions[sid]={userId:u.id,expires:Date.now()+8*3600000};audit(u,'Login','User',u.id);save();return send(res,200,{user:{id:u.id,name:u.name,email:u.email,role:u.role},csrf:sid},{'Set-Cookie':`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=28800`})}
 if(p==='/api/auth/logout'&&method==='POST'){const u=user(req);const sid=parseCookies(req).sid;if(sid)delete sessions[sid];if(u)audit(u,'Logout','User',u.id);save();return send(res,200,{ok:true},{'Set-Cookie':'sid=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'})}
 if(p==='/api/me'&&method==='GET'){const u=requireAuth(req,res);if(!u||res.writableEnded)return;return send(res,200,{id:u.id,name:u.name,email:u.email,role:u.role})}
 if(p==='/api/dashboard'&&method==='GET'){const u=requireAuth(req,res);if(!u||res.writableEnded)return;const filt=k=>db[k].filter(x=>visible(u,x));const cs=filt('customers'),ls=filt('leads'),os=filt('opportunities'),fsu=filt('followups');return send(res,200,{customers:cs.length,leads:ls.length,openLeads:ls.filter(x=>!['Lost','Converted'].includes(x.status)).length,opportunities:os.length,openOpportunities:os.filter(x=>!['Won','Lost'].includes(x.stage)).length,won:os.filter(x=>x.stage==='Won').length,lost:os.filter(x=>x.stage==='Lost').length,pipeline:os.filter(x=>!['Won','Lost'].includes(x.stage)).reduce((a,x)=>a+Number(x.amount||0),0),leadStatus:['New','Contacted','Qualified','Lost','Converted'].map(s=>({label:s,value:ls.filter(x=>x.status===s).length})),pipelineStages:['Qualification','Proposal','Negotiation','Won','Lost'].map(s=>({label:s,value:os.filter(x=>x.stage===s).length})),pendingFollowups:fsu.filter(x=>x.status==='Planned').length})}
 if(p==='/api/customers'&&method==='GET')return listBy(req,res,'customers');
 if(p==='/api/leads'&&method==='GET')return listBy(req,res,'leads');
 if(p==='/api/opportunities'&&method==='GET')return listBy(req,res,'opportunities');
 if(p==='/api/followups'&&method==='GET')return listBy(req,res,'followups');
 if(p==='/api/activities'&&method==='GET')return listBy(req,res,'activities');
 if(p==='/api/audit'&&method==='GET'){const u=requireRole(req,res,['Admin','Manager']);if(!u||res.writableEnded)return;return send(res,200,db.audit)}
 if(p==='/api/users'&&method==='GET'){const u=requireRole(req,res,['Admin','Manager']);if(!u||res.writableEnded)return;return send(res,200,db.users.map(x=>({id:x.id,name:x.name,email:x.email,role:x.role,active:x.active,failed:x.failed,lockoutEnd:x.lockoutEnd,createdAt:x.createdAt})))}
 if(p==='/api/users'&&method==='POST'){const u=requireRole(req,res,['Admin']);if(!u||res.writableEnded)return;if(!b.name||!validateEmail(b.email)||!b.password||b.password.length<8||!ROLES.includes(b.role))return send(res,400,{error:'Name, valid email, password (8+) and valid role are required'});if(db.users.some(x=>x.email.toLowerCase()===b.email.toLowerCase()))return send(res,409,{error:'Email already exists'});const nu={id:id('usr'),name:b.name,email:b.email,passwordHash:makePassword(b.password),role:b.role,active:true,failed:0,lockoutEnd:null,createdAt:now()};db.users.push(nu);audit(u,'Create','User',nu.id);save();return send(res,201,{id:nu.id,name:nu.name,email:nu.email,role:nu.role})}
 const match=p.match(/^\/api\/(customers|leads|opportunities|followups|activities)(?:\/([^/]+))?$/);if(match){const type=match[1],rid=match[2];const arr=db[type];if(method==='POST'&&!rid){const u=requireAuth(req,res);if(!u||res.writableEnded)return;let e=null,d={...b};d.id=id(type.slice(0,-1));d.createdAt=now();d.createdBy=u.id;d.assignedTo=d.assignedTo||u.id; if(type==='customers'){e=validateBase(d);if(!d.companyName)d.companyName='';if(db.customers.some(x=>x.email.toLowerCase()===String(d.email||'').toLowerCase()||x.phone===d.phone))e=e||'Duplicate customer: email or phone already exists.';d.status=d.status||'Active'} if(type==='leads'){e=validateBase(d);if(!d.status||!['New','Contacted','Qualified','Unqualified','Converted','Lost'].includes(d.status))e=e||'Lead status is required and must be valid.';if(d.expectedValue!=null&&Number(d.expectedValue)<0)e='Expected value cannot be negative.'} if(type==='opportunities'){if(!d.name)e='Opportunity name is required.';if(Number(d.amount)<=0)e='Opportunity Amount must be greater than 0.';if(Number(d.probability)<0||Number(d.probability)>100)e='Probability must be between 0 and 100.';if(!d.expectedCloseDate)e='Expected close date is required.';if(d.stage!=='Won'&&d.stage!=='Lost'&&d.expectedCloseDate<new Date().toISOString().slice(0,10))e='Expected Close Date cannot be in the past.';d.status=d.status||'Open'} if(type==='followups'){if(!d.followUpDate)e='Follow-up date is required.';if(d.status==='Planned'&&d.followUpDate<new Date().toISOString().slice(0,10))e='Follow-up date cannot be earlier than today.';d.status=d.status||'Planned'} if(type==='activities'){if(!d.activityType||!d.subject)e='Activity type and subject are required.';d.status=d.status||'Open'} if(e)return send(res,400,{error:e});arr.push(d);audit(u,'Create',type.slice(0,-1),d.id);save();return send(res,201,d)}
 const u=requireAuth(req,res);if(!u||res.writableEnded)return;const item=arr.find(x=>x.id===rid);if(!item)return send(res,404,{error:'Record not found'});if(!visible(u,item))return send(res,403,{error:'Forbidden'});
 if(method==='GET')return send(res,200,item);if(method==='PUT'){let e=null,d={...item,...b,updatedAt:now()};if(type==='customers'){e=validateBase(d);if(db.customers.some(x=>x.id!==rid&&(x.email.toLowerCase()===String(d.email||'').toLowerCase()||x.phone===d.phone)))e=e||'Email or phone already exists.'}if(type==='opportunities'){if(Number(d.amount)<=0)e='Opportunity Amount must be greater than 0.';if(Number(d.probability)<0||Number(d.probability)>100)e='Probability must be between 0 and 100.';if(d.stage!=='Won'&&d.stage!=='Lost'&&d.expectedCloseDate<new Date().toISOString().slice(0,10))e='Expected Close Date cannot be in the past.'}if(type==='followups'&&d.status==='Planned'&&d.followUpDate<new Date().toISOString().slice(0,10))e='Follow-up date cannot be earlier than today.';if(e)return send(res,400,{error:e});Object.assign(item,d);audit(u,'Update',type.slice(0,-1),rid);save();return send(res,200,item)}if(method==='DELETE'){if(u.role==='SalesExecutive'&&type!=='activities')return send(res,403,{error:'Forbidden'});arr.splice(arr.indexOf(item),1);audit(u,'Delete',type.slice(0,-1),rid);save();return send(res,200,{ok:true})}}
 if(p==='/api/reports/pipeline'&&method==='GET'){const u=requireRole(req,res,['Admin','Manager']);if(!u||res.writableEnded)return;const os=db.opportunities;const rows=['Qualification','Proposal','Negotiation','Won','Lost'].map(stage=>({stage,amount:os.filter(x=>x.stage===stage).reduce((a,x)=>a+Number(x.amount||0),0),weighted:os.filter(x=>x.stage===stage).reduce((a,x)=>a+Number(x.amount||0)*Number(x.probability||0)/100,0),count:os.filter(x=>x.stage===stage).length}));return send(res,200,rows)}
 send(res,404,{error:'Not found'})}
const server=http.createServer(async(req,res)=>{if(req.url.startsWith('/api/')){try{return await api(req,res)}catch(e){console.error(e);return send(res,500,{error:'Internal server error'})}}const p=new URL(req.url,'http://x').pathname;if(p==='/'||p==='/index.html')return html(res,'index.html');if(p.startsWith('/static/')){const f=path.join(ROOT,p.slice(1));if(fs.existsSync(f))return fs.createReadStream(f).pipe(res)}if(p.startsWith('/')){const f=path.join(PUBLIC,p.slice(1));if(fs.existsSync(f)&&fs.statSync(f).isFile()){res.writeHead(200,{'Content-Type':mime(f)});return fs.createReadStream(f).pipe(res)}}send(res,404,{error:'Not found'})});function mime(f){return {'.css':'text/css','.js':'text/javascript','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon'}[path.extname(f)]||'text/plain'}server.listen(PORT,()=>console.log(`AcxiomCRM running at http://localhost:${PORT}`));
